# Step 1: Use a Node.js base image
FROM node:18.14.2

# Step 2: Set the working directory
WORKDIR /app

# Step 3: Copy package.json and package-lock.json
COPY package*.json /app

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application code
COPY . /app

# Step 6: Generate Prisma client
RUN npx prisma generate

# Step 7: Expose the port the app runs on
EXPOSE 3000

# Step 8: Define the command to run the app
CMD ["npm", "run","start"]
